syntax = "proto3";

package envoy.extensions.filters.http.ext_proc.v3;

option java_package = "io.envoyproxy.envoy.extensions.filters.http.ext_proc.v3";
option java_outer_classname = "ProcessingModeProto";
option java_multiple_files = true;
option go_package = "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/ext_proc/v3;ext_procv3";

message ProcessingMode {
  enum HeaderSendMode {
    DEFAULT = 0;
    SEND = 1;
    SKIP = 2;
  }

  enum BodySendMode {
    NONE = 0;
    STREAMED = 1;
    BUFFERED = 2;
    BUFFERED_PARTIAL = 3;
    FULL_DUPLEX_STREAMED = 4;
    GRPC = 5;
  }

  HeaderSendMode request_header_mode = 1;
  HeaderSendMode response_header_mode = 2;
  BodySendMode request_body_mode = 3;
  BodySendMode response_body_mode = 4;
  HeaderSendMode request_trailer_mode = 5;
  HeaderSendMode response_trailer_mode = 6;
}
